name: test

on: push

jobs:
  test-without-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: delaguardo/setup-clojure@12.1
        with:
          lein: 2.10.0

      - run: lein test

  test-with-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: delaguardo/setup-clojure@12.1
        with:
          lein: 2.10.0

      - run: lein with-profile +agent test